#!/bin/sh

set -e

if [ -z "$1" ] || [ -z "$2" ]
	then
		echo "Bad call : BuildScript {x86_64|arm} {Release|Debug}\n"
		exit 1
fi

LIB_NAME=openal-soft
PLATFORM=linux.${1}
BUILD_TYPE=${2}

SOURCE_DIR=./repositories/${LIB_NAME}
BUILD_DIR=./builds/${PLATFORM}-${BUILD_TYPE}/${LIB_NAME}
INSTALL_DIR=./output/${PLATFORM}-${BUILD_TYPE}

echo "\n======================== Configuring '${LIB_NAME}' for '${PLATFORM}-${BUILD_TYPE}' ... ========================\n"

cmake -S ${SOURCE_DIR} -B ${BUILD_DIR} -G "Ninja" \
-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
-DCMAKE_C_FLAGS=-fPIC \
-DCMAKE_CXX_FLAGS=-fPIC \
-DC_FLAGS=-fPIC \
-DLIBTYPE=STATIC \
-DALSOFT_DLOPENL=On \
-DALSOFT_WERROR=Off \
-DALSOFT_UTILS=On \
-DALSOFT_NO_CONFIG_UTIL=Off \
-DALSOFT_EXAMPLES=Off \
-DALSOFT_TESTS=Off \
-DALSOFT_INSTALL=On \
-DALSOFT_INSTALL_CONFIG=On \
-DALSOFT_INSTALL_HRTF_DATA=On \
-DALSOFT_INSTALL_AMBDEC_PRESETS=On \
-DALSOFT_INSTALL_EXAMPLES=Off \
-DALSOFT_INSTALL_UTILS=Off \
-DALSOFT_UPDATE_BUILD_VERSION=Off \
-DALSOFT_EAX=Off \
-DALSOFT_SEARCH_INSTALL_DATADIR=Off \
-DALSOFT_STATIC_LIBGCC=Off \
-DALSOFT_STATIC_STDCXX=Off \
-DALSOFT_CPUEXT_SSE=On \
-DALSOFT_REQUIRE_SSE=Off \
-DALSOFT_CPUEXT_SSE2=On \
-DALSOFT_REQUIRE_SSE2=Off \
-DALSOFT_CPUEXT_SSE3=On \
-DALSOFT_REQUIRE_SSE3=Off \
-DALSOFT_CPUEXT_SSE4_1=On \
-DALSOFT_REQUIRE_SSE4_1=Off \
-DALSOFT_CPUEXT_NEON=On \
-DALSOFT_REQUIRE_NEON=Off \
-DALSOFT_ENABLE_SSE2_CODEGEN=On \
-DALSOFT_RTKIT=On \
-DALSOFT_REQUIRE_RTKIT=Off \
-DALSOFT_BACKEND_PIPEWIRE=On \
-DALSOFT_REQUIRE_PIPEWIRE=Off \
-DALSOFT_BACKEND_PULSEAUDIO=On \
-DALSOFT_REQUIRE_PULSEAUDIO=Off \
-DALSOFT_BACKEND_ALSA=On \
-DALSOFT_REQUIRE_ALSA=Off \
-DALSOFT_BACKEND_OSS=Off \
-DALSOFT_REQUIRE_OSS=Off \
-DALSOFT_BACKEND_SOLARIS=Off \
-DALSOFT_REQUIRE_SOLARIS=Off \
-DALSOFT_BACKEND_SNDIO=Off \
-DALSOFT_REQUIRE_SNDIO=Off \
-DALSOFT_BACKEND_JACK=On \
-DALSOFT_REQUIRE_JACK=Off \
-DALSOFT_BACKEND_COREAUDIO=Off \
-DALSOFT_REQUIRE_COREAUDIO=Off \
-DALSOFT_BACKEND_OBOE=Off \
-DALSOFT_REQUIRE_OBOE=Off \
-DALSOFT_BACKEND_OPENSL=Off \
-DALSOFT_REQUIRE_OPENSL=Off \
-DALSOFT_BACKEND_PORTAUDIO=On \
-DALSOFT_REQUIRE_PORTAUDIO=Off \
-DALSOFT_BACKEND_SDL2=Off \
-DALSOFT_REQUIRE_SDL2=Off \
-DALSOFT_BACKEND_WAVE=On \
-DALSOFT_EMBED_HRTF_DATA=On

echo "\n======================== Building ... ========================\n"

cmake --build ${BUILD_DIR} --config ${BUILD_TYPE}

echo "\n======================== Installing ... ========================\n"

cmake --install ${BUILD_DIR} --config ${BUILD_TYPE}

echo "\n======================== Success ! ========================\n"
